routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return redirect('products');
});

Route::group(['prefix' => 'products', 'as' => 'products.'], function(){
    Route::get('/', ['as' => 'list', 'uses' => 'ProductController@index']);
    Route::get('/crawl', ['as' => 'crawl', 'uses' => 'ProductController@crawl']);
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @author Deepu
     *
     * @var array
     */
    protected $fillable = ['name', 'price', 'created_at'];
}

app/Models/Settings.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Settings extends Model
{
    
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
use Carbon\Carbon;

class ProductController extends Controller
{
    /**
     * Constructor
     *
     * @author Deepu
     *
     */
    public function __construct()
    {
        $this->products = [];
    }

    /**
     * Show the list of products
     *
     * @author Deepu
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        $perPage = 20;
        $qry = Product::orderBy('id', 'desc');
        if ($request->has('search')) {
            $qry->where('name', 'like', '%'.$request->search.'%');
        }
        $products = $qry->paginate($perPage);
        if ($products->currentPage() > $products->lastPage()) {
            $products = $products->paginate($perPage, ['*'], 'page', $products->lastPage());
        }

        return \View::make('products.list')
            ->with('title', 'Products')
            ->with('perPage', $perPage)
            ->with('products', $products)
            ->with('search', $request->search)
            ->with('btcPrice', getBitCoinPrice());

    }

    /**
     * Crawl data from external website
     *
     * @author Deepu
     *
     * @return \Illuminate\View\View
     */
    public function crawl()
    {
        $this->fetchAndSaveProducts('&page=1');
        $i = 1;
        while (count($this->products) <= 100) {
            if (count($this->products) == 100) {
                break;
            }
            $this->fetchAndSaveProducts('&page='.(++$i));
        }
        Product::insert($this->products);
        return redirect()->route('products.list')->with('status', 'Products crawling complete!');
    }

    /**
     * Crawl data from external website
     *
     * @author Deepu
     *
     * @return void
     */
    private function fetchAndSaveProducts($pageStr)
    {
        $url = "https://www.flipkart.com/search?q=watches".$pageStr;

       	$curl = curl_init($url);
        curl_setopt($curl, CURLOPT_USERAGENT, "Mozilla/5.0 (Windows; U; Windows NT 10.10; labnol;) ctrlq.org");
        curl_setopt($curl, CURLOPT_FAILONERROR, true);
        curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        $html = curl_exec($curl);
        curl_close($curl);
		
        if (! empty($curl)) {
            $domd = new \DOMDocument;
            libxml_use_internal_errors(true);
            $domd->loadHTML($html);
            $xp = new \DOMXPath($domd);

            $results = $xp->query("//*[@class='_2B099V']");
            foreach($results as $key => $result) {
                if (count($this->products) == 100) {
                    break;
                }
                $price = $result->getElementsByTagName('a')->item(1)->getElementsByTagName('div')->item(1)->nodeValue;
                $this->products[] = [
                    'name' => $result->getElementsByTagName('a')->item(0)->getAttribute('title'),
                    'price' => filter_var($price, FILTER_SANITIZE_NUMBER_FLOAT),
                    'created_at' => Carbon::now()
                ];
            }
        }
    }
}

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Hugo 0.79.0">
        <meta name="csrf-token" content="{{ csrf_token() }}" />
        <title>{{ $title }}</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <link href="{!! asset('css/app.css') !!}" media="all" rel="stylesheet" type="text/css" />

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    </head>
  
    <body>
        <header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
            <p class="h5 my-0 me-md-auto fw-normal">Store</p>
            <nav class="my-2 my-md-0 me-md-3">
                <a class="p-2 text-dark" href="{{ route('products.list') }}">Products</a>
                <a class="p-2 text-dark" href="{{ route('products.crawl') }}">Crawl</a>
            </nav>
        </header>

        <main class="container">

            @yield('content')

            <footer class="pt-4 my-md-5 pt-md-5 border-top">
                <div class="row">
                    <div class="col-12 col-md">
                        <small class="d-block mb-3 text-muted">&copy; 2020-2021</small>
                    </div>
                </div>
            </footer>
        </main>
    </body>
</html>

resources/views/products/list.blade.php
@extends('layouts.master')

@section('content')
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif

    <form class="form-inline" method="get">
        <div class="row align-items-center">
            <div class="col-md-9">
                <input name="search" id="search" class="form-control" placeholder="Search product by name" value="{{ $search }}">
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-primary mb-2 search-btn">Search</button>
                <a href="{{ route('products.list') }}">
                    <button type="button" class="btn btn-info mb-2 search-btn">Reset</button>
                </a>
            </div>
        </div>
    </form>

    @if ($products->count())
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Price (INR)</th>
                    <th scope="col">Price (BTC)</th>
                    <th scope="col">Created At</th>
                </tr>
            </thead>
            <tbody>
                @foreach($products as $key => $product)
                    <tr>
                        <th scope="row">{{ $key + $products->firstItem() }}</th>
                        <td title="{{ $product->name }}">
                            {{ strlen($product->name) > 30 ? substr($product->name, 0, 50)."..." : $product->name  }}
                        </td>
                        <td>{{ $product->price }}</td>
                        <td>{{ number_format((float)($product->price * $btcPrice), 6, '.', '') }}</td>
                        <td>{{ $product->created_at }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        {{ $products->appends(request()->except('page'))->links() }}
    @else
        <div> No results! </div>
    @endif
@endsection

<script type="text/javascript">
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>